# Generated by Django 5.2.10 on 2026-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
    ]
