# Generated by Django 5.2.10 on 2026-02-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Actual time spent in minutes'),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current timer started', null=True),
        ),
    ]
