# Generated by Django 5.2.10 on 2026-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_time_spent_task_timer_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes - task auto-completes when timer reaches this', null=True),
        ),
    ]
