# Generated by Django 5.2.10 on 2026-02-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Task is in archive instead of deleted'),
        ),
    ]
